Dj mb handle restricted
Path-Check/gaen-mobile pull request #677
Opened 2020-11-17 17:13 UTC by devinjameson

Why: currently, there are various cases in which we do not present the correct information to the user on how to enable Exposure Notifications. These cases arise on the ActivateExposureNotifications and ExposureDetectionStatus screens.

This commit:
- Updates the exposureNotifications.request function in the PermissionsContext to not only request authorization from the GAEN API, but also return the authorization status determined from the request to the GAEN API
- Adds a side effect to the ActivateExposureNotifications screen to navigate to the next screen in the Activation flow if the exposure notification status is enabled
- Adds an Alert to the ActiveExposureNotifications screen that tells the user how to enable exposure notifications if they request authorization from the GAEN API, but need to change something in the app settings in order for exposure notifications to be enabled
- Updates the copy for the Alert that explains to the user how to enable exposure notifications in the app settings

Co-Authored-By: John Schoeman <johnschoeman1617@gmail.com>
Co-Authored-By: Matt Buckley <matt@nicethings.io>

![gif1](https://user-images.githubusercontent.com/39350030/99423117-3c998480-28ce-11eb-808d-b9958dbe4f49.gif)
![gif2](https://user-images.githubusercontent.com/39350030/99423121-3dcab180-28ce-11eb-9a2e-557e24406fd7.gif)

2020-11-17 21:02 UTC, mattThousand requested changes
Nice @devinjameson! 

@juancruzgs when you have a moment, could you update the android `requestExposureNotificationAuthorization` return type to be an array/list containing `[AUTHORIZED, ENABLED/DISABLED`], instead of `success` or `null`? (I believe those are the current return types)

2020-11-17 21:16 UTC, mattThousand commented on src/gaen/nativeModule.ts
> +    if (e.underlyingError.includes("ENErrorDomain error 13.")) {
👍

2020-11-17 22:45 UTC, devinjameson commented
@mattThousand Is this all set?

2020-11-18 16:33 UTC, johnschoeman approved these changes

2020-11-18 17:04 UTC, johnschoeman commented
@mattThousand I believe your requested changes have been resolved, going to merge this in as its blocking a few things.

2020-11-18 17:04 UTC, merged