GAEN-645, checking for phone numbers used every 15 minutes in callbac…
Path-Check/gaen-mobile pull request #879
Opened 2021-03-16 19:27 UTC by lundjrl

…k form

#### Why:

Users can repeatedly spam the callback form with their phone number, this solution makes a timestamp on the first submit and saves the phone number. Only after 15 minutes can that phone number be reused on the same device.

#### This commit:

#### Screenshots:

#### How to test:

#### Linked issues:

---

2021-03-16 19:31 UTC, lundjrl commented
Note: This build fails one of the "describe" jest tests in Form.spec.tsx

2021-03-19 17:33 UTC, artgibson commented on src/Callback/Form.tsx
> +    await AsyncStorage.setItem("LastPhoneNumber", phoneNumber)
@lundjrl let's not store the phone number, cap the number of successful attempts to 2 per 15 minutes. Update error messages to handle that also.

2021-03-23 19:10 UTC, lundjrl commented on src/Callback/Form.tsx
> +    await AsyncStorage.setItem("LastPhoneNumber", phoneNumber)
@artgibson  This should work without storing the phone number in local storage. We just check to see if the user has completed two submissions in the past 15 minutes and throw an error if so.

2021-03-30 10:41 UTC, lundjrl commented on src/Callback/Form.tsx
> +    await AsyncStorage.setItem("LastPhoneNumber", phoneNumber)
@artgibson  can you approve so we can merge into develop?

2021-04-01 01:10 UTC, artgibson commented on src/Callback/Form.tsx
> +  /* Wait for 15 minutes to pass before submitting another phonenumber after two have been submitted. */
@lundjrl clean up this doc

2021-04-01 01:10 UTC, artgibson commented on src/locales/en.json
> +    "maxed_submission_requests": "You have reached the max number of submissions, please wait 15 minutes to resubmit.",
15 to 5 minutes

2021-04-08 19:44 UTC, artgibson requested changes
@lundjrl a unit test is currently failing.

2021-04-12 18:55 UTC, lundjrl commented
@artgibson I added a test case for the Callback form changes.

2021-04-16 19:27 UTC, artgibson commented
lgtm

2021-04-16 19:32 UTC, artgibson approved these changes

2021-04-16 19:33 UTC, merged